- Proszę, oto zabawka
- Miś, niech będzie...
- Chcesz następną?
- Tak!
- Proszę, oto zabawka
- Hurra: Kotek
- Chcesz następną?
- Tak!
- Proszę, oto zabawka
- Łeeeee to tylko Lisek
- Chcesz następną?
- Tak!
- Proszę, oto zabawka
- Hurra: Krokodyl
- Chcesz następną?
- Tak!
- No i koniec!
